Pull requests
kaizencc/github-merit-badger pull request #40
Opened 2023-07-25 21:39 UTC by kaizencc

Fixes #

2023-07-25 21:39 UTC, kaizencc reviewed
dsVdls;kjf

2023-07-25 21:41 UTC, aws-cdk-automation requested changes
test review

2023-07-26 14:44 UTC, aws-cdk-automation reviewed
test review

2023-07-26 14:45 UTC, aws-cdk-automation commented
comment

2023-07-26 19:00 UTC, kaizencc commented
comment

2023-07-26 19:00 UTC, kaizencc reviewed
comment

2023-07-26 19:06 UTC, scanlonp requested changes
Please fix.

2023-07-26 19:07 UTC, vinayak-kukreja approved these changes

2023-07-26 19:07 UTC, vinayak-kukreja commented on README.md
> +Example Pull Request
This looks great 🎉

2023-07-26 19:10 UTC, scanlonp requested changes
Looks better

2023-07-26 19:13 UTC, vinayak-kukreja commented
Fantastic!!

2023-07-26 19:14 UTC, vinayak-kukreja reviewed
Amazing work!!

2023-07-26 19:51 UTC, kaizencc reviewed
edit

2023-07-26 19:55 UTC, kaizencc commented
reg comment

2023-07-26 19:59 UTC, closed without merging